---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Stop the deployment if requested
  ansible.builtin.assert:
    msg: 'Stopping before task-gather-facts'
    that: (kubeinit_stop_before_task | default('')) != 'task-gather-facts'
  tags: omit_from_grapher

#
# Gather facts needed to create the hypervisor_hosts group
#

- name: Add playbook context facts
  ansible.builtin.set_fact:
    container_run: "{{ kubeinit_container_run | default(false) | bool }}"
  delegate_to: 'kubeinit-facts'
  delegate_facts: true

- name: Gather kubeinit secrets
  ansible.builtin.include_role:
    name: kubeinit.kubeinit.kubeinit_prepare
    tasks_from: gather_kubeinit_secrets.yml
    public: true
  vars:
    _param_secret_names:
      - kubeinit-ssh-key

- name: Gather additional facts from localhost for kubeinit
  ansible.builtin.include_role:
    name: kubeinit.kubeinit.kubeinit_libvirt
    tasks_from: gather_host_facts.yml
    public: true
  vars:
    _param_gather_host: 'localhost'

- name: Lookup remote_user from command-line
  ansible.builtin.set_fact:
    kubeinit_cli_remote_user: "{{ lookup('kubeinit.kubeinit.cli_args', 'remote_user') }}"

- name: Check for empty remote user when running from kubeinit container
  ansible.builtin.assert:
    msg:
      - "You must provide the user for the playbook when running from the kubeinit container."
      - "e.g. --user root"
    that: not hostvars['kubeinit-facts'].container_run or kubeinit_cli_remote_user|length > 0

- name: Define kubeinit remote_user
  ansible.builtin.set_fact:
    local_user: "{{ ansible_user_id }}"
    local_home: "{{ ansible_user_dir }}"
    local_ssh_dir: "{{ ansible_user_dir + '/.ssh' }}"
    remote_user: "{{ kubeinit_cli_remote_user if (kubeinit_cli_remote_user|length > 0) else ansible_user_id }}"
    ssh_keytype: "{{ hostvars['kubeinit-env'].ssh_keytype }}"
  delegate_to: 'kubeinit-facts'
  delegate_facts: true

- name: Prepare cluster topology using kubeinit_spec command-line specification
  ansible.builtin.set_fact:
    kubeinit_spec_parts: "{{ kubeinit_spec.split('-') | default([]) }}"

- name: Assert we have a minimum number of spec parts
  ansible.builtin.assert:
    msg: "Usage: -e kubeinit_spec=<distro>-<driver>-<controllers>-<computes>-<hypervisors>[-<ignored>]"
    that: kubeinit_spec_parts|length >= 5

- name: Set facts from spec parts
  ansible.builtin.set_fact:
    kubeinit_spec_distro: "{{ kubeinit_spec_parts[0] }}"
    kubeinit_spec_driver: "{{ kubeinit_spec_parts[1] }}"
    kubeinit_spec_controller_count: "{{ kubeinit_spec_parts[2] }}"
    kubeinit_spec_compute_count: "{{ kubeinit_spec_parts[3] }}"
    kubeinit_spec_hypervisor_count: "{{ kubeinit_spec_parts[4] }}"

- name: Set fact for the spec distro role
  ansible.builtin.set_fact:
    kubeinit_distro_role: "{{ hostvars['kubeinit-facts'].distro_facts[kubeinit_spec_distro].role }}"
  when: hostvars['kubeinit-facts'].distro_facts[kubeinit_spec_distro] is defined

- name: Assert spec constraints
  ansible.builtin.assert:
    that:
      - kubeinit_distro_role is defined
      - kubeinit_spec_driver in ['libvirt']
      - kubeinit_spec_controller_count in ['1', '3', '5']
      - kubeinit_spec_compute_count|int >= 0
      - kubeinit_spec_hypervisor_count|int >= 1

- name: Load kubeinit_cluster_spec from yaml into a dictionary
  ansible.builtin.set_fact:
    kubeinit_cluster_map: "{{ kubeinit_cluster_spec | from_yaml }}"
  when: kubeinit_cluster_spec is defined

- name: Define kubeinit_cluster_name
  ansible.builtin.set_fact:
    kubeinit_cluster_name: "{{ kubeinit_cluster_map['cluster_name'] | default(kubeinit_spec_distro + 'cluster') }}"

- name: Add kubeinit_cluster_name to kubeinit-facts
  ansible.builtin.set_fact:
    cluster_name: "{{ kubeinit_cluster_name }}"
  delegate_to: 'kubeinit-facts'
  delegate_facts: true

- name: Add kubeinit_cluster_map entries to kubeinit-cluster host
  ansible.builtin.set_fact:
    cluster_domain: "{{ kubeinit_cluster_map['cluster_domain'] | default(omit) }}"
    hypervisor_name_pattern: "{{ kubeinit_cluster_map['hypervisor_name_pattern'] | default(omit) }}"
    controller_name_pattern: "{{ kubeinit_cluster_map['controller_name_pattern'] | default(omit) }}"
    compute_name_pattern: "{{ kubeinit_cluster_map['compute_name_pattern'] | default(omit) }}"
  delegate_to: 'kubeinit-cluster'
  delegate_facts: true
  when: kubeinit_cluster_map is defined

- name: Load post_deployment_services_spec from yaml into a list
  ansible.builtin.set_fact:
    post_deployment_services_list: "{{ post_deployment_services_spec | from_yaml }}"
  when: post_deployment_services_spec is defined

- name: Add post_deployment_services_list to kubeinit-cluster host
  ansible.builtin.set_fact:
    post_deployment_services: "{{ post_deployment_services_list }}"
  delegate_to: 'kubeinit-cluster'
  delegate_facts: true
  when: post_deployment_services_list | default([]) | length > 0

- name: Load extra_roles_spec from yaml into a list
  ansible.builtin.set_fact:
    extra_roles_list: "{{ extra_roles_spec | from_yaml }}"
  when: extra_roles_spec is defined

- name: Add extra_roles_list to kubeinit-cluster host
  ansible.builtin.set_fact:
    extra_roles: "{{ extra_roles_list }}"
  delegate_to: 'kubeinit-cluster'
  delegate_facts: true
  when: extra_roles_list | default([]) | length > 0

- name: Load hypervisor_hosts_spec from yaml into a list of dictionaries
  ansible.builtin.set_fact:
    hypervisor_hosts_map_list: "{{ hypervisor_hosts_spec | from_yaml }}"
  when: hypervisor_hosts_spec is defined

- name: Create hypervisor hosts for undefined cluster hypervisors
  ansible.builtin.add_host:
    name: "{{ hypervisor_hosts_map_list[ansible_loop.index0]['host'] | default(hostvars['kubeinit-cluster'].hypervisor_name_pattern | format(ansible_loop.index)) }}"
    group: ['hypervisor_hosts','all_hosts']
    type: hypervisor
  loop: "{{ range(kubeinit_spec_hypervisor_count|int) | list }}"
  loop_control:
    extended: true

- name: Assign defaults to existing cluster hypervisors
  ansible.builtin.set_fact:
    ansible_connection: 'smart'
    ansible_user: "{{ hostvars['kubeinit-facts'].remote_user }}"
  loop: "{{ range(kubeinit_spec_hypervisor_count|int) | list }}"
  loop_control:
    extended: true
  delegate_to: "{{ groups['hypervisor_hosts'][ansible_loop.index0] }}"
  delegate_facts: true

- name: Add remaining spec vars to hypervisor_hosts group
  ansible.builtin.set_fact:
    ansible_host: "{{ hypervisor_hosts_map_list[ansible_loop.index0]['ansible_host'] | default(omit) }}"
    ssh_hostname: "{{ hypervisor_hosts_map_list[ansible_loop.index0]['ssh_hostname'] | default(omit) }}"
    ssh_username: "{{ hypervisor_hosts_map_list[ansible_loop.index0]['ssh_username'] | default(omit) }}"
  loop: "{{ groups['hypervisor_hosts'] }}"
  loop_control:
    extended: true
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hypervisor_hosts_map_list is defined

#
# Setup bastion host
#
- name: Parse bastion_host_spec into a dictionary if defined
  ansible.builtin.set_fact:
    bastion_host_map: "{{ bastion_host_spec | from_yaml }}"
  when: bastion_host_spec is defined

- name: Assert bastion_host_spec does not have both target and ansible_host keys
  ansible.builtin.assert:
    msg: "The bastion_host_spec cannot have both target and ansible_host keys."
    that: bastion_host_map['target'] is not defined or bastion_host_map['ansible_host'] is not defined
  when: bastion_host_map is defined

- name: Define default bastion target and ansible_host from spec target
  ansible.builtin.set_fact:
    default_bastion_target: "{{ bastion_host_map['target'] }}"
  when: bastion_host_map['target'] | default('') | length > 0

- name: Define default bastion target and ansible_host from spec ansible_host
  ansible.builtin.set_fact:
    default_bastion_target: "{{ bastion_host_map['host'] | default('bastion') }}"
  when: bastion_host_map['ansible_host'] | default('') | length > 0

- name: Use the first hypervisor if neither bastion host spec or group defines a target or ansible_host
  ansible.builtin.set_fact:
    kubeinit_bastion_host: "{{ default_bastion_target | default(groups['hypervisor_hosts'] | first) }}"

- name: Create a host entry for the bastion host when it does not have a target
  ansible.builtin.add_host:
    name: "{{ kubeinit_bastion_host }}"
    group: 'all_hosts'
    type: bastion
    ansible_host: "{{ bastion_host_map['ansible_host'] }}"
  when: bastion_host_map['ansible_host'] | default('') | length > 0

#
# Setup ovn-central host
#
- name: Parse ovn_central_host_spec into a dictionary if defined
  ansible.builtin.set_fact:
    ovn_central_host_map: "{{ ovn_central_host_spec | from_yaml }}"
  when: ovn_central_host_spec is defined

- name: Assert ovn_central_host_spec does not have both target and ansible_host keys
  ansible.builtin.assert:
    msg: "The ovn_central_host_spec cannot have both target and ansible_host keys."
    that: ovn_central_host_map['target'] is not defined or ovn_central_host_map['ansible_host'] is not defined
  when: ovn_central_host_map is defined

- name: Define default ovn-central target and ansible_host from spec target
  ansible.builtin.set_fact:
    default_ovn_central_target: "{{ ovn_central_host_map['target'] }}"
  when: ovn_central_host_map['target'] | default('') | length > 0

- name: Define default ovn-central target and ansible_host from spec ansible_host
  ansible.builtin.set_fact:
    default_ovn_central_target: "{{ ovn_central_host_map['host'] | default('ovn-central') }}"
  when: ovn_central_host_map['ansible_host'] | default('') | length > 0

- name: Use the first hypervisor if ovn-central host spec does now define a target
  ansible.builtin.set_fact:
    kubeinit_ovn_central_host: "{{ default_ovn_central_target | default(groups['hypervisor_hosts'] | first) }}"

- name: Create a host entry for the ovn-central host when it does not have a target
  ansible.builtin.add_host:
    name: "{{ kubeinit_ovn_central_host }}"
    group: 'all_hosts'
    type: 'ovn-central'
    ansible_host: "{{ ovn_central_host_map['ansible_host'] }}"
  when: ovn_central_host_map['ansible_host'] | default('') | length > 0

- name: Add kubeinit_spec facts to cluster facts
  ansible.builtin.set_fact:
    distro: "{{ kubeinit_spec_distro }}"
    distro_role: "{{ kubeinit_distro_role }}"
    controller_count: "{{ kubeinit_spec_controller_count }}"
    compute_count: "{{ kubeinit_spec_compute_count }}"
  delegate_to: 'kubeinit-cluster'
  delegate_facts: true

- name: Set more cluster facts from inventory groups and kubeinit_spec
  ansible.builtin.set_fact:
    kubeinit_cluster_distro: "{{ kubeinit_spec_distro }}"
    kubeinit_cluster_distro_role: "{{ kubeinit_distro_role }}"
    kubeinit_cluster_domain: "{{ hostvars['kubeinit-cluster'].cluster_domain }}"
    kubeinit_cluster_fqdn: "{{ kubeinit_cluster_name + '.' + hostvars['kubeinit-cluster'].cluster_domain }}"

- name: Create local_ssh_dir folder if needed
  ansible.builtin.file:
    path: "{{ hostvars['kubeinit-facts'].local_ssh_dir }}"
    state: directory
    mode: '0700'

- name: Copy kubeinit-ssh-key secret into local_ssh_dir
  ansible.builtin.copy:
    content: "{{ lookup('unvault', hostvars['kubeinit-secrets'].secrets['kubeinit-ssh-key']) }}"
    dest: "{{ hostvars['kubeinit-facts'].local_ssh_dir + '/id_' + hostvars['kubeinit-facts'].ssh_keytype }}"
    mode: '0600'
  when: hostvars['kubeinit-facts'].container_run|bool

- name: Set kubeinit_cluster_keypair_path fact
  ansible.builtin.set_fact:
    kubeinit_cluster_keypair_path: "{{ hostvars['kubeinit-facts'].local_ssh_dir + '/' + hostvars['kubeinit-facts'].cluster_name + '_id_' + hostvars['kubeinit-facts'].ssh_keytype }}"

- name: Generate an OpenSSH keypair for the cluster
  community.crypto.openssh_keypair:
    path: "{{ kubeinit_cluster_keypair_path }}"
    type: "{{ hostvars['kubeinit-facts'].ssh_keytype }}"
    comment: "{{ hostvars['kubeinit-facts'].cluster_name + ' ansible-controller' }}"
    regenerate: 'never'
  register: _result_keypair

- name: Set authorized_key fact from keypair
  ansible.builtin.set_fact:
    authorized_key: "{{ _result_keypair.public_key + ' ' + _result_keypair.comment }}"

- name: Add cluster authorized_key to root account of all hosts
  ansible.posix.authorized_key:
    user: root
    key: "{{ authorized_key }}"
    state: present
  become: true
  become_user: root
  loop: "{{ groups['all_hosts'] }}"
  delegate_to: "{{ item }}"
  delegate_facts: true

- name: Check if kubeinit ssh config exists
  ansible.builtin.stat:
    path: "{{ hostvars['kubeinit-facts'].local_ssh_dir + '/kubeinit_config' }}"
  register: _result_kubeinit_ssh_config_stat

- name: Check if ssh config exists
  ansible.builtin.stat:
    path: "{{ hostvars['kubeinit-facts'].local_ssh_dir + '/config' }}"
  register: _result_ssh_config_stat
  when: not _result_kubeinit_ssh_config_stat.stat.exists

- name: Set kubeinit_cluster_ssh_include_paths
  ansible.builtin.set_fact:
    kubeinit_cluster_ssh_include_paths:
      "{{ [_result_kubeinit_ssh_config_stat.stat.path] if (_result_kubeinit_ssh_config_stat.stat.exists) else [_result_ssh_config_stat.stat.path] if (_result_ssh_config_stat.stat.exists) else [] }}"

- name: Set kubeinit_cluster_ssh_config fact
  ansible.builtin.set_fact:
    kubeinit_cluster_ssh_config: "{{ hostvars['kubeinit-facts'].local_ssh_dir + '/' + hostvars['kubeinit-facts'].cluster_name + '_config' }}"

- name: Create ssh config file from template
  ansible.builtin.include_role:
    name: kubeinit.kubeinit.kubeinit_prepare
    tasks_from: create_host_ssh_config.yml
    public: true
  vars:
    _param_hosts: "{{ groups['all_hosts'] }}"
    _param_ssh_keytype: "{{ hostvars['kubeinit-facts'].ssh_keytype }}"
    _param_keypair_path: "{{ kubeinit_cluster_keypair_path }}"
    _param_dest_path: "{{ kubeinit_cluster_ssh_config }}"
    _param_include_paths: "{{ kubeinit_cluster_ssh_include_paths }}"

- name: Ensure kubeinit remote_user fact is set to root
  ansible.builtin.set_fact:
    remote_user: 'root'
  delegate_to: 'kubeinit-facts'
  delegate_facts: true

- name: Add ansible_ssh_extra_args to all hosts
  ansible.builtin.set_fact:
    ansible_ssh_extra_args: "{{ '-i ' + kubeinit_cluster_keypair_path + ' -F ' + kubeinit_cluster_ssh_config }}"
    ansible_user: "{{ hostvars['kubeinit-facts'].remote_user }}"
  loop: "{{ groups['all_hosts'] }}"
  delegate_to: "{{ item }}"
  delegate_facts: true

- name: Confirm that we have ansible host connectivity
  ansible.builtin.ping:
  loop: "{{ groups['all_hosts'] }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
