---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

###
# The set of kubernetes distributions supported by Kubeinit.
#
# - name: the formal name for the distro
# - role: the role that provides the distro specific tasks.
#
distro_facts:
  k8s:
    name: 'Vanilla CNCF Kubernetes'
    role: kubeinit_k8s
  ocp:
    name: 'OpenShift Container Platform'
    role: kubeinit_openshift
  okd:
    name: 'Origin Distribution of Kubernetes'
    role: kubeinit_openshift
