---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Add authorized key to hypervisor host
  ansible.posix.authorized_key:
    user: "{{ hostvars[hypervisor_host].ssh_username | default(hostvars['kubeinit-facts'].remote_user) }}"
    key: "{{ ssh_pubkey }}"
    comment: "{{ ssh_comment }}"
    state: present
  vars:
    hypervisor_host: "{{ inventory_hostname }}"
  become: "{{ true if (hostvars[hypervisor_host].ssh_username | default(hostvars['kubeinit-facts'].remote_user) == 'root') else false }}"
  become_user: "{{ hostvars[hypervisor_host].ssh_username | default(hostvars['kubeinit-facts'].remote_user) }}"
  delegate_to: "{{ hypervisor_host }}"

- name: Confirm access to hypervisor from setup host and user
  ansible.builtin.shell: |
    set -o pipefail
    ssh \
        -F {{ hostvars[setup_host_name].deploy_ssh_config }} \
        {{ hostvars[hypervisor_host].ssh_username | default(hostvars['kubeinit-facts'].remote_user) }}@{{ hostvars[hypervisor_host].ansible_host }} 'echo connected' || true
  args:
    executable: /bin/bash
  register: _result
  changed_when: "_result.rc == 0"
  retries: 30
  delay: 10
  until: "'connected' in _result.stdout"
  vars:
    hypervisor_host: "{{ inventory_hostname }}"
  delegate_to: "{{ setup_host_name }}"
