---
# Copyright kubeinit contributors
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Gather facts from the cluster hypervisor hosts
  hosts: kubeinit_hypervisors
  become: false
  gather_subset: "!all,network"
  gather_facts: true
  tasks:
    - name: Skip play if playbook_terminated
      ansible.builtin.meta: end_play
      when: hostvars['kubeinit-facts'].playbook_terminated | default(false)
      tags:
        - omit_from_grapher
        - tag_gather_facts
      run_once: true

    - name: Gather additional hypervisor facts kubeinit will use during deployment
      tags: tag_gather_facts
      delegate_facts: true
      block:
        - name: Gather facts from each hypervisor in the deployment
          ansible.builtin.include_role:
            name: kubeinit.ansible.gather_host_facts
            public: true
          vars:
            gather_host: "{{ inventory_hostname }}"
